global:
  api_key: my_service_user_api_key
  tenant_url: https://my-tenant.sentinelone.net
  log_level: trace
command:
  provision:
    account:
      csv_separator: tab
      csv_source: ./examples/accounts.tsv
      reactivate_expired_account: true
      reset_first_user_password: false
  version:
    short: false
    verbose: true
