global:
  api_key: my_service_user_api_key
  tenant_url: https://my-tenant.sentinelone.net
  log_level: trace
command:
  provision:
    account:
      source: ./examples/accounts.yaml
      reactivate_expired_account: true
      
  version:
    short: false
    verbose: true
